### ISSUE TITLE
Fails to build with VTK-9.2.2: no member named 'GetRenderWindow' in 'QVTKOpenGLStereoWidget'; did you mean 'renderWindow'?

### ISSUE THREAD

**Issue by yurivict** [thliebig/QCSXCAD#10]
```
/wrkdirs/usr/ports/cad/qcsxcad/work/QCSXCAD-0.6.2-9-g3f09a8b/QVTKStructure.cpp:116:13: error: no member named 'GetRenderWindow' in 'QVTKOpenGLStereoWidget'; did you mean 'renderWindow'?
        VTKWidget->GetRenderWindow()->AddRenderer(ren);
                   ^~~~~~~~~~~~~~~
                   renderWindow
/usr/local/include/vtk-9.2/QVTKOpenGLStereoWidget.h:93:20: note: 'renderWindow' declared here
  vtkRenderWindow* renderWindow() const { return this->VTKOpenGLWindow->renderWindow(); }
                   ^
```

**Comment by thliebig** [comment]
Well looking into the vtk 9.2 release notes confirms that vtk has made some API changes.
I'm not sure why a library this big does stuff like this. But I guess checking for all such API changes will require some work.
Until then, QCSXCAD does not work with vtk >=9.2

**Comment by yurivict** [comment]
This [patch](https://cgit.freebsd.org/ports/tree/cad/qcsxcad/files/patch-QVTKStructure.cpp) solves it.

**Comment by thliebig** [comment]
Does it work with older vtk aswell? And down to which version of vtk? Otherwise it will need an ugly #ifdef switch...

**Comment by StefanBruens** [comment]
`renderWindow` and `setRenderWindow` have been added in 9.0(rc) only, and the semantically equivalent `GetRenderWindow`/`SetRenderWindow` have been deprecated at the same time. Thats unfortunately a quite short time window.

According to https://repology.org/project/vtk/badges, all current distributions have VTK 9.
- Fedora 34 has 9.0.3, 37 has 9.1.0
- Debian 10 has 7.1.1, but 9 in Backports. EOL since 2022-09. Debian 11 has 9.0.1
- Ubuntu has 9.1.0 in 22.04 and 22.10.
- openSUSE has 9.1.0 in 15.4 and 9.2.2 in TW.

From all the distributions above, only openSUSE packages (Q)CSXCAD.

@thliebig - is it really worth to keep up VTK 7 and 8 support?
